#!/usr/bin/env python3
"""Build the read-only Q4 historical import bundle.

The command accepts all input and output paths explicitly.  It reads local raw
evidence and the content-addressed archive, deduplicates by bytes, and emits a
single canonical JSON object containing an import report and an empty Q4
dataset.  Historical rows retain their original Q3/prior/failure roles; no
historical row is relabelled as Q4_TRAIN, and no performance number is
manufactured from a summary.

No model/runtime package is imported.  The output is created with O_EXCL and
0600, so an existing report cannot be silently replaced.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import os
import sys
import types
from pathlib import Path
from typing import Any, Iterable, Mapping


def _load_offline_modules() -> tuple[Any, Any]:
    """Load ``ironmule.q4_*`` without executing ironmule.__init__."""
    root = Path(__file__).resolve().parents[1]
    package = sys.modules.get("ironmule")
    if package is None or not hasattr(package, "__path__"):
        package = types.ModuleType("ironmule")
        package.__path__ = [str(root / "ironmule")]
        package.__package__ = "ironmule"
        sys.modules["ironmule"] = package
    for name in ("evidence", "q4_contracts", "q4_corpus"):
        full_name = f"ironmule.{name}"
        if full_name in sys.modules:
            continue
        spec = importlib.util.spec_from_file_location(full_name, root / "ironmule" / f"{name}.py")
        if spec is None or spec.loader is None:
            raise RuntimeError(f"cannot load offline module {name}")
        module = importlib.util.module_from_spec(spec)
        sys.modules[full_name] = module
        spec.loader.exec_module(module)
    return sys.modules["ironmule.q4_contracts"], sys.modules["ironmule.q4_corpus"]


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _prereg_hash(path: Path | None) -> str:
    if path is not None and path.is_file():
        return _sha256(path)
    # This is a stable marker for an import performed before the prereg path
    # was supplied.  It is not evidence and cannot be mistaken for its hash.
    return hashlib.sha256(b"Q4_PREREGISTRATION_NOT_SUPPLIED").hexdigest()


def build_import_bundle(
    raw_roots: Iterable[str | os.PathLike[str]],
    archive_root: str | os.PathLike[str] | None,
    output: str | os.PathLike[str] | None = None,
    *,
    preregistration: str | os.PathLike[str] | None = None,
) -> dict[str, Any]:
    """Return and optionally atomically-create a deterministic import bundle."""
    _, corpus_mod = _load_offline_modules()
    sources: list[tuple[str, Path]] = []
    for index, root in enumerate(raw_roots):
        path = Path(root)
        if not path.is_dir():
            raise ValueError(f"raw root is not a directory: {path}")
        sources.append((f"raw-{index}", path))
    if archive_root is not None:
        archive = Path(archive_root)
        if not archive.is_dir():
            raise ValueError(f"archive root is not a directory: {archive}")
        sources.append(("archive", archive))
    if not sources:
        raise ValueError("at least one raw root or archive root is required")
    corpus = corpus_mod.inspect_sources(sources)
    dataset = corpus.to_dataset(_prereg_hash(Path(preregistration) if preregistration is not None else None))
    report = corpus.report()
    report["dataset_id"] = dataset.dataset_id
    report["preregistration_sha256"] = dataset.preregistration_sha256
    report["source_roots"] = [alias for alias, _ in sources]
    bundle = {
        "schema": "ironmule.q4_import_bundle.v1",
        "import_report": report,
        "dataset": dataset.to_dict(),
    }
    # Canonical JSON is generated by the contract module, after all validation.
    contracts_mod, _ = _load_offline_modules()
    # ``payload_sha256`` is intentionally non-circular: it covers the
    # canonical envelope with this field omitted, not a claimed full self-hash.
    encoded = contracts_mod.canonical_json(bundle).encode("utf-8")
    bundle["import_report"]["payload_sha256"] = hashlib.sha256(encoded).hexdigest()
    encoded = contracts_mod.canonical_json(bundle).encode("utf-8")
    if output is not None:
        output_path = Path(output)
        flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL
        fd = os.open(output_path, flags, 0o600)
        try:
            with os.fdopen(fd, "wb") as stream:
                stream.write(encoded)
                stream.write(b"\n")
        except Exception:
            # Do not leave a partially-written artifact that looks canonical.
            try:
                output_path.unlink()
            except OSError:
                pass
            raise
    return bundle


def validate_import_bundle(bundle: Mapping[str, Any]) -> bool:
    """Validate the non-circular canonical payload checksum on a loaded bundle."""
    contracts_mod, _ = _load_offline_modules()
    if not isinstance(bundle, Mapping) or bundle.get("schema") != "ironmule.q4_import_bundle.v1":
        return False
    report = bundle.get("import_report")
    if not isinstance(report, Mapping) or not isinstance(report.get("payload_sha256"), str):
        return False
    payload = json.loads(contracts_mod.canonical_json(bundle))
    payload["import_report"].pop("payload_sha256", None)
    expected = hashlib.sha256(contracts_mod.canonical_json(payload).encode("utf-8")).hexdigest()
    return report["payload_sha256"] == expected


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--raw-root", action="append", required=True, help="research/raw directory (repeatable)")
    parser.add_argument("--archive-root", required=False, help="content-addressed evidence archive")
    parser.add_argument("--preregistration", help="frozen Q4 preregistration file")
    parser.add_argument("--output", required=True, help="new local report/dataset JSON path")
    args = parser.parse_args(argv)
    build_import_bundle(args.raw_root, args.archive_root, args.output, preregistration=args.preregistration)
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
