"""Small, offline-only building blocks for Friday's optimization memory.

The package deliberately contains no model runner and no hardware probing.  It
only provides the immutable data contract used by later, separately gated
components.
"""

from .canonical import (
    CanonicalJSONError,
    DEFAULT_MAX_BYTES,
    DEFAULT_MAX_DEPTH,
    DEFAULT_MAX_INTEGER_DIGITS,
    canonical_bytes,
    canonical_dumps,
    canonical_json,
    canonical_json_bytes,
    loads_strict,
    strict_json_loads,
    sha256_hex,
)
from .memory import (
    APPLICATION_ID,
    GENESIS_HASH,
    IntegrityError,
    IntegrityReport,
    MemoryConflictError,
    MemoryLimitError,
    OptimizationMemoryV2,
    OptimizationMemoryError,
    ReadOnlyMemoryView,
    UnsafeDatabaseError,
)
from .candidates import CANDIDATE_IDS, CandidateError, CandidateRegistry, CandidateSpec
from .corpus import CorpusAuditor, CorpusInventory, CorpusIssue, EvidenceContract, ManifestVerifier, NormalizedRecord, RecordSink, normalize_record
from .dataset import DatasetBuilder, DatasetCard, DatasetSnapshot, LeakageReport, detect_leakage
from .evaluator import CalibrationReport, CorrectnessResult, EvaluationError, Evaluator, MetricSample, ResourceResult, ShadowDecision, evaluate_candidate
from .fingerprint import EnvironmentFingerprint, ExactFingerprint, Fingerprint, ModelFingerprint, RuntimeFingerprint, WorkloadFingerprint
from .profiles import AtomicProfileStore, OptimizerProfile, ProfileError, ProfileMode, ProfileSelection
from .readiness import HardwareLease, LeaseBusy, LeaseError, MacProbe, MacSystemProbe, OutputTruncated, ProbeSnapshot, ReadinessDecision, ReadinessError, ReadinessGate, ReadinessPolicy, check_readiness
from .record_bridge import MemoryRecordSink, normalized_to_memory_records
from .session import AdapterResult, ProfileContract, PromotionAuthorization, PromotionGate, SessionController, SessionError, SessionState, StageSpec, SubprocessStageRunner, TransitionAudit, VerifiedStageRunner
from .dashboard import DashboardError, DashboardHandler, DashboardServer, DashboardService, serve
from .ironmule_adapter import CheckoutValidation, CheckoutValidationError, IronMuleAdapterError, IronMuleCheckoutBinding, IronMuleTuneAdapter, ParsedIronMuleResult, ResultValidationError, StagedStageSpec, UnsupportedStage
from .real_session import (
    ALLOWED_CANDIDATE,
    ALLOWED_STAGES,
    FINGERPRINT_SCHEMA,
    PLAN_SCHEMA,
    PREREG_SCHEMA,
    RESULT_SCHEMA,
    FingerprintReport,
    RealFingerprintReport,
    Preregistration,
    RealSessionController,
    SessionExecutionOutcome,
    RealSessionError,
    RealSessionUnavailable,
    SessionPlan,
    RealSessionPlan,
    SessionResult,
    build_session_plan,
    collect_fingerprint,
    run_session,
    optimizer_source_manifest,
    optimizer_identity,
    start_authorization_hash,
)
from .cli import main
from .records import (
    DataPhase,
    FeatureLabelPhase,
    OptimizationRecord,
    QualityClass,
    RecordKind,
)
from .history import (
    HISTORY_KIND_PHASE,
    HistoryError,
    HistoryIntegrityError,
    HistoryReader,
    HistoryWriter,
    SessionEvent,
)
from .orchestrator import (
    audit,
    build_dataset,
    doctor,
    DoctorReport,
    ImportReport,
    import_inventory,
    OfflineOrchestrator,
    OptimizerConfig,
    OptimizerOrchestrator,
    OptimizerStatus,
    OrchestratorConfig,
    ShadowRequest,
)

__all__ = [
    "APPLICATION_ID",
    "CanonicalJSONError",
    "DEFAULT_MAX_BYTES",
    "DEFAULT_MAX_DEPTH",
    "DEFAULT_MAX_INTEGER_DIGITS",
    "DataPhase",
    "FeatureLabelPhase",
    "GENESIS_HASH",
    "IntegrityReport",
    "IntegrityError",
    "MemoryConflictError",
    "MemoryLimitError",
    "OptimizationMemoryError",
    "OptimizationMemoryV2",
    "ReadOnlyMemoryView",
    "OptimizationRecord",
    "QualityClass",
    "RecordKind",
    "UnsafeDatabaseError",
    "canonical_bytes",
    "canonical_dumps",
    "canonical_json",
    "canonical_json_bytes",
    "loads_strict",
    "strict_json_loads",
    "sha256_hex",
    "CANDIDATE_IDS",
    "CandidateError",
    "CandidateRegistry",
    "CandidateSpec",
    "CorpusAuditor",
    "CorpusInventory",
    "CorpusIssue",
    "EvidenceContract",
    "ManifestVerifier",
    "NormalizedRecord",
    "RecordSink",
    "normalize_record",
    "DatasetBuilder",
    "DatasetCard",
    "DatasetSnapshot",
    "LeakageReport",
    "detect_leakage",
    "CalibrationReport",
    "CorrectnessResult",
    "EvaluationError",
    "Evaluator",
    "MetricSample",
    "ResourceResult",
    "ShadowDecision",
    "evaluate_candidate",
    "EnvironmentFingerprint",
    "ExactFingerprint",
    "Fingerprint",
    "ModelFingerprint",
    "RuntimeFingerprint",
    "WorkloadFingerprint",
    "AtomicProfileStore",
    "OptimizerProfile",
    "ProfileError",
    "ProfileMode",
    "ProfileSelection",
    "HardwareLease",
    "ProbeSnapshot",
    "ReadinessDecision",
    "ReadinessGate",
    "ReadinessPolicy",
    "check_readiness",
    "LeaseBusy",
    "LeaseError",
    "MacProbe",
    "MacSystemProbe",
    "OutputTruncated",
    "ReadinessError",
    "MemoryRecordSink",
    "normalized_to_memory_records",
    "AdapterResult",
    "SessionController",
    "SessionError",
    "SessionState",
    "StageSpec",
    "SubprocessStageRunner",
    "ProfileContract",
    "PromotionAuthorization",
    "PromotionGate",
    "TransitionAudit",
    "VerifiedStageRunner",
    "DashboardError",
    "DashboardHandler",
    "DashboardServer",
    "DashboardService",
    "serve",
    "CheckoutValidation",
    "CheckoutValidationError",
    "IronMuleAdapterError",
    "IronMuleCheckoutBinding",
    "IronMuleTuneAdapter",
    "ParsedIronMuleResult",
    "ResultValidationError",
    "StagedStageSpec",
    "UnsupportedStage",
    "ALLOWED_CANDIDATE",
    "ALLOWED_STAGES",
    "FINGERPRINT_SCHEMA",
    "PLAN_SCHEMA",
    "PREREG_SCHEMA",
    "RESULT_SCHEMA",
    "FingerprintReport",
    "RealFingerprintReport",
    "Preregistration",
    "RealSessionController",
    "SessionExecutionOutcome",
    "RealSessionError",
    "RealSessionUnavailable",
    "SessionPlan",
    "RealSessionPlan",
    "SessionResult",
    "build_session_plan",
    "collect_fingerprint",
    "run_session",
    "optimizer_source_manifest",
    "optimizer_identity",
    "start_authorization_hash",
    "main",
    "DoctorReport",
    "audit",
    "build_dataset",
    "doctor",
    "HistoryError",
    "HistoryIntegrityError",
    "HistoryReader",
    "HistoryWriter",
    "HISTORY_KIND_PHASE",
    "ImportReport",
    "import_inventory",
    "OfflineOrchestrator",
    "OptimizerConfig",
    "OptimizerOrchestrator",
    "OptimizerStatus",
    "OrchestratorConfig",
    "SessionEvent",
    "ShadowRequest",
]
