#!/usr/bin/env python3
"""A closed measure-decide loop that picks an execution plan on its own.

This is the piece the project actually claims: not a human choosing a candidate
and checking it, but a loop that explores a space, measures each option against
a frozen threshold, discards what fails, refines around what survives, and
confirms its own winner before reporting it.

Three rounds:

  1. explore  -- a fixed candidate set, measured paired against the baseline
  2. refine   -- neighbours of whatever survived round 1, generated by the loop
  3. confirm  -- the leader re-measured independently; an unreplicated win is
                 reported as unconfirmed rather than as a result

Every candidate passes a correctness gate before its timing counts: an execution
plan may reorder work, never change a single bit of the result.  The statistics
are imported from ``measure_dispatch_plan`` rather than reimplemented, because a
second copy of an estimator is a second chance to get it subtly wrong.

Run with --execute; without it nothing is imported or measured.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import math
import statistics
import subprocess
import sys
import time
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]

# tools/ is loaded as loose scripts, not a package.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _bench import BudgetGuard, release_gate, require_ac_power, run_persisted  # noqa: E402

_SPEC = importlib.util.spec_from_file_location(
    "measure_dispatch_plan", Path(__file__).resolve().parent / "measure_dispatch_plan.py"
)
_PLAN = importlib.util.module_from_spec(_SPEC)
_SPEC.loader.exec_module(_PLAN)

paired_ratio = _PLAN.paired_ratio
clears_threshold = _PLAN.clears_threshold
hierarchical_bootstrap = _PLAN.hierarchical_bootstrap

FIXTURE_SEED = 4051312678
OPERAND_POOL_SEED = 20260821
SHAPE = 2048
MAX_OPERANDS = 16
# Frozen before the loop runs.  A candidate must clear this to be a finding.
MDE = 0.05
EXPLORE_BLOCKS = 20
CONFIRM_BLOCKS = 25
CONFIRM_REPLICATES = 3
BOOTSTRAP_SEED = 0x10091_2026
# Measured on this device: the first samples after a pause are inflated.
WARMUP_DISCARD = 3

EXPLORE_BATCH_SIZES = (2, 4, 8, 16)


def neighbours(batch_size: int, tried: set[int]) -> list[int]:
    """Batch sizes adjacent to a winner, skipping anything already measured.

    Refinement is what makes this a search rather than a checklist: the loop
    proposes these itself, based on which candidate survived.
    """

    candidates = {batch_size - 2, batch_size - 1, batch_size + 1, batch_size + 2}
    return sorted(
        size for size in candidates if 2 <= size <= MAX_OPERANDS and size not in tried
    )


def summarize(log_ratios: list[float]) -> dict[str, object]:
    summary = paired_ratio(log_ratios)
    summary["clears_mde"] = clears_threshold(summary, MDE)
    summary["log_ratios"] = list(log_ratios)
    return summary


def rank(results: list[dict]) -> list[dict]:
    """Best first, ranked by the *upper* confidence bound, not the point estimate.

    Ranking by the point estimate picks the luckiest outlier: the best of several
    noisy candidates is optimistic by construction, and the independent
    confirmation then fails.  Measured here -- ranking by ratio produced a
    confirmed winner in only one run out of three, while the point estimates of
    the chosen candidates (0.750, 0.741) regressed to 0.87-0.96 on re-measurement.

    Ranking by ``ci_high`` asks a different question: not "which looked best
    once" but "which is reliably good".  A wide interval is penalised exactly as
    much as its uncertainty warrants.  Only candidates that cleared the frozen
    threshold can lead at all.
    """

    return sorted(
        results,
        key=lambda entry: (
            not entry["clears_mde"],
            entry.get("ci_high", entry["ratio"]),
        ),
    )


def _self_check() -> int:
    """Offline checks of the loop's decision logic; no GPU, no MLX."""

    assert neighbours(4, set()) == [2, 3, 5, 6]
    assert neighbours(4, {2, 3}) == [5, 6]
    assert neighbours(2, set()) == [3, 4], neighbours(2, set())
    assert neighbours(16, set()) == [14, 15], neighbours(16, set())

    win = summarize([math.log(0.80)] * 20)
    assert win["clears_mde"]
    null = summarize([0.0] * 20)
    assert not null["clears_mde"]

    ordered = rank(
        [
            {"name": "null", "ratio": 0.99, "ci_high": 1.05, "clears_mde": False},
            {"name": "weak", "ratio": 0.93, "ci_high": 0.94, "clears_mde": True},
            {"name": "strong", "ratio": 0.80, "ci_high": 0.85, "clears_mde": True},
        ]
    )
    assert [entry["name"] for entry in ordered] == ["strong", "weak", "null"]

    # A confirmed-but-worse candidate must still outrank an unconfirmed better one.
    ordered = rank(
        [
            {"name": "unconfirmed", "ratio": 0.70, "ci_high": 1.10, "clears_mde": False},
            {"name": "confirmed", "ratio": 0.90, "ci_high": 0.93, "clears_mde": True},
        ]
    )
    assert ordered[0]["name"] == "confirmed"

    # The lucky-outlier case: a great point estimate with a wide interval must
    # lose to a slightly worse one that is actually reliable.
    ordered = rank(
        [
            {"name": "lucky", "ratio": 0.75, "ci_high": 0.94, "clears_mde": True},
            {"name": "reliable", "ratio": 0.84, "ci_high": 0.87, "clears_mde": True},
        ]
    )
    assert ordered[0]["name"] == "reliable", [e["name"] for e in ordered]

    print(json.dumps({"self_check": "pass", "checks": 9}))
    return 0


class Harness:
    """Owns the operands and turns a batch size into a measurable plan."""

    def __init__(self, guard: BudgetGuard | None = None) -> None:
        import mlx.core as mx
        import numpy as np

        sys.path.insert(0, str(PROJECT_ROOT))
        from friday_h0.benchmark import _generate_fixture

        self.guard = guard or BudgetGuard()
        self.mx = mx
        self.np = np
        fixture = _generate_fixture(np, FIXTURE_SEED, shape=SHAPE)
        self.a = mx.array(fixture.a)
        gpu_started = time.perf_counter()
        mx.eval(self.a)
        mx.synchronize()
        self.guard.record_gpu(time.perf_counter() - gpu_started)
        rng = np.random.Generator(np.random.PCG64(OPERAND_POOL_SEED))
        self.pool = [
            mx.array(rng.uniform(-1.0, 1.0, (SHAPE, SHAPE)).astype(np.float16))
            for _ in range(MAX_OPERANDS)
        ]
        gpu_started = time.perf_counter()
        mx.eval(*self.pool)
        mx.synchronize()
        self.guard.record_gpu(time.perf_counter() - gpu_started)
        self.references = []
        for operand in self.pool:
            gpu_started = time.perf_counter()
            self.references.append(
                np.array(mx.matmul(self.a, operand), copy=False).astype(np.float32)
            )
            self.guard.record_gpu(time.perf_counter() - gpu_started)

    def _serial(self, n: int) -> list:
        produced = []
        for operand in self.pool[:n]:
            value = self.mx.matmul(self.a, operand)
            self.mx.eval(value)
            self.mx.synchronize()
            produced.append(value)
        return produced

    def _batched(self, n: int) -> list:
        produced = [self.mx.matmul(self.a, operand) for operand in self.pool[:n]]
        self.mx.eval(produced)
        self.mx.synchronize()
        return produced

    def correctness_holds(self, n: int) -> bool:
        """An execution plan may reorder work; it may not change one bit."""

        for plan in (self._serial, self._batched):
            gpu_started = time.perf_counter()
            values = plan(n)
            self.guard.record_gpu(time.perf_counter() - gpu_started)
            for index, value in enumerate(values):
                observed = self.np.array(value, copy=False).astype(self.np.float32)
                if float(self.np.abs(observed - self.references[index]).max()) != 0.0:
                    return False
        return True

    def measure(self, n: int, blocks: int) -> list[float]:
        """Paired log-ratios of batched against serial for one batch size."""

        for _ in range(WARMUP_DISCARD):
            gpu_started = time.perf_counter()
            self._serial(n)
            self._batched(n)
            self.guard.record_gpu(time.perf_counter() - gpu_started)
        log_ratios = []
        for _ in range(blocks):
            start = time.perf_counter_ns()
            self._serial(n)
            serial_ns = time.perf_counter_ns() - start
            start = time.perf_counter_ns()
            self._batched(n)
            batched_ns = time.perf_counter_ns() - start
            self.guard.record_gpu((serial_ns + batched_ns) / 1e9)
            log_ratios.append(math.log(batched_ns / serial_ns))
        return log_ratios


def run(explore_blocks: int, confirm_blocks: int) -> dict[str, object]:
    guard = BudgetGuard()
    harness = Harness(guard)
    rounds: list[dict] = []
    tried: set[int] = set()

    def evaluate(batch_size: int, blocks: int) -> dict:
        guard.before_candidate()
        try:
            if not harness.correctness_holds(batch_size):
                return {"name": f"batched_{batch_size}", "batch_size": batch_size,
                        "rejected": "correctness", "clears_mde": False, "ratio": 1.0,
                        "log_ratios": []}
            summary = summarize(harness.measure(batch_size, blocks))
            summary.update({"name": f"batched_{batch_size}", "batch_size": batch_size,
                            "rejected": None})
            return summary
        finally:
            guard.finish_candidate()

    # Round 1 -- explore
    explored = [evaluate(size, explore_blocks) for size in EXPLORE_BATCH_SIZES]
    tried.update(EXPLORE_BATCH_SIZES)
    rounds.append({"round": "explore", "results": explored})
    survivors = [entry for entry in explored if entry["clears_mde"]]

    # Round 2 -- refine around whatever survived, chosen by the loop itself
    refined: list[dict] = []
    if survivors:
        leader = rank(survivors)[0]
        proposals = neighbours(leader["batch_size"], tried)
        refined = [evaluate(size, explore_blocks) for size in proposals]
        tried.update(proposals)
        rounds.append(
            {"round": "refine", "around": leader["batch_size"],
             "proposed": proposals, "results": refined}
        )

    everything = explored + refined
    ranked = rank(everything)
    leader = ranked[0] if ranked and ranked[0]["clears_mde"] else None

    # Round 3 -- confirm the leader independently, or report nothing
    confirmation = None
    if leader is not None:
        guard.before_candidate()
        try:
            replicate_logs = []
            for replicate in range(CONFIRM_REPLICATES):
                if replicate:
                    guard.required_break()
                replicate_logs.append(
                    harness.measure(leader["batch_size"], confirm_blocks)
                )
        finally:
            guard.finish_candidate()
        aggregate = hierarchical_bootstrap(replicate_logs, seed=BOOTSTRAP_SEED)
        aggregate["clears_mde"] = clears_threshold(aggregate, MDE)
        aggregate["replicate_ratios"] = [
            round(math.exp(statistics.median(logs)), 4) for logs in replicate_logs
        ]
        aggregate["replicate_log_ratios"] = replicate_logs
        confirmation = aggregate
        rounds.append({"round": "confirm", "batch_size": leader["batch_size"],
                       "result": aggregate})

    accepted = bool(confirmation and confirmation["clears_mde"])
    budget = guard.summary()
    return {
        "mde": MDE,
        "rounds": rounds,
        "candidates_measured": len(everything),
        "survivors": len([e for e in everything if e["clears_mde"]]),
        "selected": leader["name"] if leader else None,
        "selected_batch_size": leader["batch_size"] if leader else None,
        "confirmation": confirmation,
        "verdict": "optimization_confirmed" if accepted else "no_confirmed_optimization",
        "effect_percent": (
            round(100.0 * (confirmation["ratio"] - 1.0), 2) if accepted else None
        ),
        "gpu_work_seconds": budget["gpu_work_seconds"],
        "wall_seconds": budget["wall_seconds"],
        "budget": budget,
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="optimization_loop", allow_abbrev=False)
    parser.add_argument("--execute", action="store_true")
    parser.add_argument("--self-check", action="store_true")
    parser.add_argument("--explore-blocks", type=int, default=EXPLORE_BLOCKS)
    parser.add_argument("--confirm-blocks", type=int, default=CONFIRM_BLOCKS)
    args = parser.parse_args(argv)

    gated = release_gate(args, _self_check)
    if gated is not None:
        return gated
    if not 2 <= args.explore_blocks <= 100:
        raise SystemExit("explore-blocks must be between 2 and 100")
    if not 2 <= args.confirm_blocks <= 100:
        raise SystemExit("confirm-blocks must be between 2 and 100")

    power = require_ac_power()

    def operation() -> dict[str, object]:
        report = run(args.explore_blocks, args.confirm_blocks)
        report["power_source"] = power
        return report

    report = run_persisted("loop", operation)
    print(json.dumps(report, ensure_ascii=False, sort_keys=True, indent=1))
    return 0 if report["verdict"] == "optimization_confirmed" else 1


if __name__ == "__main__":
    raise SystemExit(main())
